[2022-09-08T19:21:31.943+0500] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: expectation_dag.expect_values_in_set manual__2022-09-08T14:21:24.959695+00:00 [queued]>
[2022-09-08T19:21:31.949+0500] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: expectation_dag.expect_values_in_set manual__2022-09-08T14:21:24.959695+00:00 [queued]>
[2022-09-08T19:21:31.949+0500] {taskinstance.py:1368} INFO - 
--------------------------------------------------------------------------------
[2022-09-08T19:21:31.949+0500] {taskinstance.py:1369} INFO - Starting attempt 1 of 1
[2022-09-08T19:21:31.949+0500] {taskinstance.py:1370} INFO - 
--------------------------------------------------------------------------------
[2022-09-08T19:21:31.963+0500] {taskinstance.py:1389} INFO - Executing <Task(PythonOperator): expect_values_in_set> on 2022-09-08 14:21:24.959695+00:00
[2022-09-08T19:21:31.967+0500] {standard_task_runner.py:52} INFO - Started process 1077920 to run task
[2022-09-08T19:21:31.969+0500] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'expectation_dag', 'expect_values_in_set', 'manual__2022-09-08T14:21:24.959695+00:00', '--job-id', '41', '--raw', '--subdir', 'DAGS_FOLDER/expectation_dag.py', '--cfg-path', '/tmp/tmp5qb5cp_o', '--error-file', '/tmp/tmp4xcd057b']
[2022-09-08T19:21:31.970+0500] {standard_task_runner.py:80} INFO - Job 41: Subtask expect_values_in_set
[2022-09-08T19:21:32.023+0500] {task_command.py:371} INFO - Running <TaskInstance: expectation_dag.expect_values_in_set manual__2022-09-08T14:21:24.959695+00:00 [running]> on host shahroze
[2022-09-08T19:21:32.084+0500] {taskinstance.py:1581} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=expectation_dag
AIRFLOW_CTX_TASK_ID=expect_values_in_set
AIRFLOW_CTX_EXECUTION_DATE=2022-09-08T14:21:24.959695+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-09-08T14:21:24.959695+00:00
[2022-09-08T19:21:32.088+0500] {taskinstance.py:1902} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/usr/local/lib/python3.10/dist-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/shahroze/airflow/dags/expectations.py", line 23, in expectation1
    raise ValueError('File not parsed completely/correctly')
ValueError: File not parsed completely/correctly
[2022-09-08T19:21:32.091+0500] {taskinstance.py:1407} INFO - Marking task as FAILED. dag_id=expectation_dag, task_id=expect_values_in_set, execution_date=20220908T142124, start_date=20220908T142131, end_date=20220908T142132
[2022-09-08T19:21:32.103+0500] {standard_task_runner.py:92} ERROR - Failed to execute job 41 for task expect_values_in_set (File not parsed completely/correctly; 1077920)
[2022-09-08T19:21:32.141+0500] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-09-08T19:21:32.182+0500] {local_task_job.py:279} INFO - 0 downstream tasks scheduled from follow-on schedule check
